### ISSUE TITLE
How to use the built in toolbar?

### ISSUE THREAD

**Issue by ssoulless** [Voog/wysihtml-rails#4]
Hi followed steps, I added the `//= require wysihtml-toolbar`for use the built in toolbar, and in the js I have exact the same you suggested:

```javascript
<script>
   var editor = new wysihtml5.Editor("wysihtml5-textarea", { // id of textarea element
      toolbar:      "wysihtml5-toolbar", // id of toolbar element
      stylesheets:  "<%= stylesheet_path('wysihtml') %>", // optional, css to style the editor's content
      parserRules:  wysihtml5ParserRules, // defined in parser rules set
      //showToolbarAfterInit: false
   });
</script>
```
However it shows an error in the console: `TypeError: null is not an object (evaluating 'this.container.querySelectorAll')`
it displays this error when the id you pass for toolbar does not exist.

How to use the built in toolbar?

**Comment by pulges** [comment]
You need to make the toolbar element to make it work. See examples:
(Simple) https://github.com/Voog/wysihtml/blob/master/examples/simple.html#L75
(Full) https://github.com/Voog/wysihtml/blob/master/examples/advanced_div.html#L184

PS: instead of passing id string to toolbar parameter you can also pass DOM element:
https://github.com/Voog/wysihtml/wiki/Configuration#toolbar
